### ISSUE TITLE
Drop opened files when switching tasks

### ISSUE THREAD

**Issue by tonich-sh** [marlomgirardi/vscode-keep-context#10]
Only one opened file "survives" after task switching.

**Comment by marlomgirardi** [comment]
Yes, the VSCode API changed a bit. I was using `onDidCloseTextDocument` and `onDidOpenTextDocument` to listen for opened and closed files since we don't have an api to access Open Editors (https://github.com/microsoft/vscode/issues/15178). Currently if you are in file `a.ts` and go to `b.ts` it runs:
- `onDidCloseTextDocument` for `a.ts`
- `onDidOpenTextDocument` for `b.ts`

**Comment by marlomgirardi** [comment]
Seems like soon this extension will be working again after 1 year of waiting 🤷‍♂️ 
https://github.com/microsoft/vscode/commit/aa69f3d7623c464aba726d12ea0d83428f43e8b9

**Comment by marlomgirardi** [comment]
Just pushed v0.3.0 replacing `TextDocument` by `Tab` and `TabGroups` seems to work 🎉
